/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataGrid;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dq
 */
public class DataGrid extends javax.swing.JFrame {
   PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Connection con;
    Koneksi db ;
    private int currentPage = 1;
    private int pageSize = 10;
       private int totalRecords = 0;
    
    /**
     * Creates new form DataGrid
     */
    public DataGrid() {
        initComponents();
        db = new Koneksi();
        con = db.con;
        totalRecords = getTotalRecords();
        loadData();
       
    }
    
    
    private int getTotalRecords(){
        int totalRecords = 0;
        try {
            String sql = "SELECT COUNT(*) FROM  data_siswa";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()){
                totalRecords = rs.getInt(1);
            }
            rs.close();
            pst.close();
            
              
        } catch (Exception e) {
            e.printStackTrace();
        }
     return  totalRecords;
        
    }
    
    
    private void loadData(){
        int offset = (currentPage - 1) * pageSize;
        
        try {
            String sql  = "SELECT * FROM data_siswa LIMIT ?,?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, offset);
            pst.setInt(2, pageSize);
            
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tblSiswa.getModel();
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
 
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        updatePaginationLabel();
    }
    
    private void updatePaginationLabel(){
        int totalPages = (int) Math.ceil((double) totalRecords / pageSize);
        pageInfoLabel.setText("Page" + currentPage + "of" + totalPages);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        tblFirst = new javax.swing.JButton();
        tblPreview = new javax.swing.JButton();
        tblNext = new javax.swing.JButton();
        tblLast = new javax.swing.JButton();
        pageInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama ", "Alamat", "Kelas"
            }
        ));
        jScrollPane1.setViewportView(tblSiswa);

        tblFirst.setText("First");
        tblFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblFirstActionPerformed(evt);
            }
        });

        tblPreview.setText("Preview");
        tblPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblPreviewActionPerformed(evt);
            }
        });

        tblNext.setText("Next");
        tblNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblNextActionPerformed(evt);
            }
        });

        tblLast.setText("Last");
        tblLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pageInfoLabel)
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblFirst)
                .addGap(72, 72, 72)
                .addComponent(tblPreview)
                .addGap(69, 69, 69)
                .addComponent(tblNext)
                .addGap(77, 77, 77)
                .addComponent(tblLast)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblLast)
                    .addComponent(tblNext)
                    .addComponent(tblPreview)
                    .addComponent(tblFirst))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblNextActionPerformed
        // TODO add your handling code here:
        if (currentPage <  (int) Math.ceil((double) totalRecords / pageSize)) {
            currentPage++;
            loadData();
        }
    }//GEN-LAST:event_tblNextActionPerformed

    private void tblPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblPreviewActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1 ){
            currentPage--;
            loadData();
        }
    }//GEN-LAST:event_tblPreviewActionPerformed

    private void tblFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblFirstActionPerformed
           currentPage = 1;
           loadData();
    }//GEN-LAST:event_tblFirstActionPerformed

    private void tblLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblLastActionPerformed
        // TODO add your handling code here:
        currentPage = (int) Math.ceil((double) totalRecords / pageSize);
        loadData();
    }//GEN-LAST:event_tblLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataGrid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageInfoLabel;
    private javax.swing.JButton tblFirst;
    private javax.swing.JButton tblLast;
    private javax.swing.JButton tblNext;
    private javax.swing.JButton tblPreview;
    private javax.swing.JTable tblSiswa;
    // End of variables declaration//GEN-END:variables
}
